name: CaseStudy5

on:
  pull_request:
  workflow_dispatch:

jobs:
  databricks-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Databricks Job
        id: run_databricks_job
        uses: databricks/run-notebook@v0
        with:
          databricks-host: ${{ secrets.DATABRICKS_HOST }}
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          workspace-notebook-path: /Workspace/Users/traininguser5@sudosu.ai/CaseStudy5
          existing-cluster-id: ${{ secrets.DATABRICKS_CLUSTER_ID }}

      - name: Download and Print Deequ Report
        if: always()
        run: |
          pip install databricks-cli jq
          databricks fs cp \
            --host "${{ secrets.DATABRICKS_HOST }}" \
            --token "${{ secrets.DATABRICKS_TOKEN }}" \
            dbfs:/FileStore/shared_uploads/traininguser5@sudosu.ai/deequ_result.json \
            ./deequ_result.json
          
          echo "------ Deequ Output from Databricks ------"
          cat deequ_result.json
          echo "-------------------------------------------"

          STATUS=$(jq -r '.result.check_status' deequ_result.json)
          if [ "$STATUS" != "Success" ]; then
            echo "Deequ checks failed"
            exit 1
          fi
          echo "Deequ checks passed"

      - name: Deequ Failure Message
        if: failure()
        run: |
          echo "Deequ failed — see DBFS report in Databricks"
